name: PR
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly and wasm utils
      run: sh scripts/init.sh
    - name: Build node 
      run: cd node && cargo build --verbose
    - name: Runtime tests
      run: cd runtime && cargo test 
